# Lab 8 - Sandeep Pandey - 8878312

In [1]:
import torch

In [2]:
# PyTorch: Dot product of two vectors
vector1_torch = torch.tensor([1, 2, 3])
vector2_torch = torch.tensor([4, 5, 6])
dot_product_torch = torch.dot(vector1_torch, vector2_torch)

# PyTorch: Matrix multiplication of two matrices
matrix1_torch = torch.tensor([[1, 2], [3, 4]])
matrix2_torch = torch.tensor([[5, 6], [7, 8]])
matrix_multiplication_torch = torch.mm(matrix1_torch, matrix2_torch)

In [3]:
dot_product_torch, matrix_multiplication_torch

(tensor(32),
 tensor([[19, 22],
         [43, 50]]))

In [4]:
import tensorflow as tf

In [5]:
# TensorFlow: Dot product of two vectors
vector1_tf = tf.constant([1, 2, 3], dtype=tf.float32)
vector2_tf = tf.constant([4, 5, 6], dtype=tf.float32)
dot_product_tf = tf.tensordot(vector1_tf, vector2_tf, axes=1)

# TensorFlow: Matrix multiplication of two matrices
matrix1_tf = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix2_tf = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
matrix_multiplication_tf = tf.matmul(matrix1_tf, matrix2_tf)

In [6]:
dot_product_tf, matrix_multiplication_tf

(<tf.Tensor: shape=(), dtype=float32, numpy=32.0>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[19., 22.],
        [43., 50.]], dtype=float32)>)